import assert from "node:assert/strict";
import test from "node:test";
import { assertBatchAction, assertEligibleComposition, beneficiaryEffective, calculateComposition } from "../lib/payment-controls.ts";

const row = (overrides: Partial<{id:string;status:string;embassyId:string;vacId:string;bookingDate:Date;visaFeePaisa:number;alreadyBatched:boolean}>={}) => ({ id:"case-1", status:"Eligible for Payment", embassyId:"italy", vacId:"isb", bookingDate:new Date("2026-09-01T00:00:00Z"), visaFeePaisa:3000000, ...overrides });
test("eligibility excludes unresolved, halted, cross-group and previously batched cases",()=>{for(const value of [row({status:"Business Decision Required"}),row({status:"Halted"}),row({vacId:"lhe"}),row({alreadyBatched:true})])assert.throws(()=>assertEligibleComposition([value],"italy","isb"));});
test("zero-amount cases are excluded from payable composition",()=>assert.throws(()=>calculateComposition([row(),row({id:"case-2",visaFeePaisa:0})]),/Zero-amount/));
test("booking-date breakup exactly reconciles to case count and integer-paisa amount",()=>{const result=calculateComposition([row(),row({id:"case-2",bookingDate:new Date("2026-09-02T00:00:00Z"),visaFeePaisa:2500001})]);assert.deepEqual(result.breakups.map(x=>[x.bookingDate,x.caseCount,x.amountPaisa]),[["2026-09-01",1,3000000],["2026-09-02",1,2500001]]);assert.equal(result.amountPaisa,5500001);});
test("beneficiary must be approved, active and effective on intended date",()=>{const base={isActive:true,approvalStatus:"APPROVED",effectiveFrom:new Date("2026-01-01"),effectiveTo:new Date("2026-12-31")};assert.equal(beneficiaryEffective(base,new Date("2026-09-01")),true);assert.equal(beneficiaryEffective({...base,isActive:false},new Date("2026-09-01")),false);assert.equal(beneficiaryEffective(base,new Date("2027-01-01")),false);});
test("maker-checker separation and locked approved composition are enforced",()=>{assert.throws(()=>assertBatchAction("Submitted for Approval","approve","same","same","Reviewed"),/cannot approve/);assert.doesNotThrow(()=>assertBatchAction("Submitted for Approval","approve","maker","checker","Reviewed totals"));assert.throws(()=>assertBatchAction("Approved","edit","maker","maker"),/blocked/);});
test("checker approval, return and rejection require remarks",()=>{assert.throws(()=>assertBatchAction("Submitted for Approval","return","maker","checker"),/mandatory/);assert.throws(()=>assertBatchAction("Submitted for Approval","reject","maker","checker","  "),/mandatory/);assert.doesNotThrow(()=>assertBatchAction("Submitted for Approval","return","maker","checker","Correct beneficiary"));});
