import test from "node:test"; import assert from "node:assert/strict"; import { assertConfirmationEligible, buildBookingBreakup, matchConfirmation, parsePaisa, validateConfirmationRecord, type CandidateBatch, type ConfirmationRecord } from "../lib/reconciliation-controls.ts";
const record:ConfirmationRecord={bankReference:"SCB-1",paymentDate:"2026-09-11",beneficiaryName:"Consulate of Italy",beneficiaryAccount:"PK18 HABB 0025",paidAmountPaisa:6000000,embassyReference:"ITALY",vacReference:"ISB"}; const candidate:CandidateBatch={id:"b1",status:"Sent to Bank",batchReference:"IBFT-1",embassyReference:"ITALY",vacReference:"ISB",beneficiaryName:"Consulate of Italy",beneficiaryAccount:"PK18HABB0025",payableAmountPaisa:6000000,paymentProcessingDate:"2026-09-11"};
test("integer paisa parsing is exact",()=>{assert.equal(parsePaisa("60000.01"),6000001);assert.throws(()=>parsePaisa("1.001"));});
test("only Sent to Bank is eligible",()=>{assert.equal(matchConfirmation(record,[{...candidate,status:"Approved"}]).outcome,"Unmatched Bank Record");assert.equal(matchConfirmation(record,[candidate]).outcome,"Matched");});
test("amount, date and beneficiary mismatches remain explicit",()=>{assert.equal(matchConfirmation({...record,paidAmountPaisa:1},[candidate]).outcome,"Amount Mismatch");assert.equal(matchConfirmation({...record,paymentDate:"2026-09-12"},[candidate]).outcome,"Date Mismatch");assert.equal(matchConfirmation({...record,beneficiaryName:"Wrong"},[candidate]).outcome,"Beneficiary Mismatch");});
test("ambiguous exact candidates are never auto-selected",()=>assert.equal(matchConfirmation(record,[candidate,{...candidate,id:"b2"}]).outcome,"Ambiguous Match"));
test("mandatory errors reject records",()=>assert.deepEqual(validateConfirmationRecord({}),["SCB_BANK_REFERENCE_REQUIRED","SCB_PAYMENT_DATE_INVALID","SCB_BENEFICIARY_REQUIRED","SCB_ACCOUNT_REQUIRED","SCB_AMOUNT_INVALID"]));
test("zero amounts are excluded from payable booking dates",()=>assert.deepEqual(buildBookingBreakup([{bookingDate:"2026-09-01",amountPaisa:0},{bookingDate:"2026-09-01",amountPaisa:100},{bookingDate:"2026-08-31",amountPaisa:200}]),[{bookingDate:"2026-08-31",caseCount:1,amountPaisa:200},{bookingDate:"2026-09-01",caseCount:1,amountPaisa:100}]));
test("unresolved confirmation output is prohibited",()=>{assert.throws(()=>assertConfirmationEligible("Amount Mismatch","Open"));assert.doesNotThrow(()=>assertConfirmationEligible("Matched","Reconciled"));});
