import test from "node:test"; import assert from "node:assert/strict"; import { zipSync, strToU8 } from "fflate"; import { duplicateBankReferences, normalizeScbDate, parseScbCsv, parseScbEvidence, parseScbPdf, parseScbXlsx, ScbParsingError } from "../lib/scb-parsers.ts";
const header="Bank Reference,Payment Date,Beneficiary Name,IBAN,Paid Amount,Embassy,VAC,Narrative";const values="SCB-42,11/09/2026,Consulate of Italy,PK18 HABB 0025,60000.01,ITALY,ISB,IBFT-42";
test("CSV semantic parsing preserves raw and normalized values",()=>{const [row]=parseScbCsv(new TextEncoder().encode(`${header}\n${values}`));assert.equal(row.raw.paymentDate,"11/09/2026");assert.equal(row.normalized.paymentDate,"2026-09-11");assert.equal(row.normalized.paidAmountPaisa,6000001);assert.equal(row.evidenceLocation,"CSV row 2");});
test("controlled SCB date formats normalize without guessing",()=>{assert.equal(normalizeScbDate("11-09-2026"),"2026-09-11");assert.equal(normalizeScbDate("11 September 2026"),"2026-09-11");assert.equal(normalizeScbDate("11-Sep-2026"),"2026-09-11");assert.throws(()=>normalizeScbDate("September 11, 2026"),ScbParsingError);assert.throws(()=>normalizeScbDate("31/02/2026"),ScbParsingError);});
test("structured XLSX is semantically extracted",()=>{const cells=[header.split(","),values.split(",")].map((row,r)=>`<row r="${r+1}">${row.map((v,c)=>`<c r="${String.fromCharCode(65+c)}${r+1}" t="inlineStr"><is><t>${v}</t></is></c>`).join("")}</row>`).join("");const bytes=zipSync({"xl/workbook.xml":strToU8(`<workbook><sheets><sheet name="SCB Confirmation" sheetId="1" r:id="rId1"/></sheets></workbook>`),"xl/_rels/workbook.xml.rels":strToU8(`<Relationships><Relationship Id="rId1" Target="worksheets/sheet1.xml"/></Relationships>`),"xl/worksheets/sheet1.xml":strToU8(`<worksheet><sheetData>${cells}</sheetData></worksheet>`)});const [parsed]=parseScbXlsx(bytes);assert.equal(parsed.normalized.bankReference,"SCB-42");assert.equal(parsed.evidenceLocation,"XLSX SCB Confirmation row 2");});
test("machine-readable PDF label values are extracted by page",()=>{const fields=["Bank Reference: SCB-42","Payment Date: 11 Sep 2026","Beneficiary Name: Consulate of Italy","IBAN: PK18HABB0025","Paid Amount: 60000.01","Embassy: ITALY","VAC: ISB","Narrative: IBFT-42"].map(v=>`(${v}) Tj`).join("\n");const pdf=`%PDF-1.4\n1 0 obj<</Type /Page>>endobj\n2 0 obj<</Length ${fields.length}>>stream\n${fields}\nendstream\nendobj\n%%EOF`;const [parsed]=parseScbPdf(new TextEncoder().encode(pdf));assert.equal(parsed.normalized.paymentDate,"2026-09-11");assert.match(parsed.evidenceLocation,/PDF page 1/);});
test("scanned and unreadable PDFs become stable parsing errors",()=>{assert.throws(()=>parseScbPdf(new TextEncoder().encode("not pdf")),(e:unknown)=>e instanceof ScbParsingError&&e.code==="SCB_PDF_UNREADABLE");assert.throws(()=>parseScbEvidence(new TextEncoder().encode("%PDF-1.4 image"),"scan.pdf","application/pdf"),(e:unknown)=>e instanceof ScbParsingError&&e.code==="SCB_PDF_IMAGE_ONLY");});

test("duplicate bank references reject the complete parsed population",()=>{const rows=parseScbCsv(new TextEncoder().encode(`${header}\n${values}\n${values}`));assert.deepEqual(duplicateBankReferences(rows),["SCB-42"]);});
