import { and, desc, eq, inArray } from "drizzle-orm";
import type { BatchItem } from "drizzle-orm/batch";
import type { AuthorizedUser } from "@/app/access";
import { getDb } from "@/db";
import { auditEvents, cases, fileUploads, paymentBatchBookingBreakups, paymentBatchCases, paymentBatches, reconciliationCaseLinks, reconciliationResolutions, reconciliationResults, scbConfirmationFiles, scbConfirmationRecords, statusHistory } from "@/db/schema";
import { assertPermission } from "@/lib/authorization";
import { assertResolutionAction, assertResolutionInput, type ResolutionAction } from "@/lib/reconciliation-resolution-controls";

export class ResolutionError extends Error { constructor(public code:string,message:string,public status=400){super(message);} }
const uid=()=>crypto.randomUUID();
export async function actOnReconciliation(input:{reconciliationId:string;action:ResolutionAction;reason:string;evidenceUploadId:string;batchId?:string;user:AuthorizedUser}){
  assertPermission(input.user.roles,["approve","return"].includes(input.action)?"reconciliation:approve":"reconciliation:resolve");assertResolutionInput(input.reason,input.evidenceUploadId);
  const db=getDb(),now=new Date(),correlationId=uid(),row=(await db.select({result:reconciliationResults,record:scbConfirmationRecords,uploaderId:scbConfirmationFiles.uploaderId}).from(reconciliationResults).innerJoin(scbConfirmationRecords,eq(scbConfirmationRecords.id,reconciliationResults.recordId)).innerJoin(scbConfirmationFiles,eq(scbConfirmationFiles.id,scbConfirmationRecords.fileId)).where(eq(reconciliationResults.id,input.reconciliationId)).limit(1))[0];if(!row)throw new ResolutionError("RECONCILIATION_NOT_FOUND","Reconciliation not found.",404);
  const evidence=(await db.select({id:fileUploads.id}).from(fileUploads).where(eq(fileUploads.id,input.evidenceUploadId)).limit(1))[0];if(!evidence)throw new ResolutionError("RESOLUTION_EVIDENCE_NOT_FOUND","Supporting evidence upload does not exist.");
  const pending=(await db.select().from(reconciliationResolutions).where(eq(reconciliationResolutions.reconciliationId,input.reconciliationId)).orderBy(desc(reconciliationResolutions.createdAt)).limit(1))[0];
  try{assertResolutionAction({action:input.action,status:row.result.status,actorId:input.user.id,requesterId:pending?.requestedBy,uploaderId:row.uploaderId,matcherId:row.result.matchedBy,roles:input.user.roles});}catch(error){throw new ResolutionError((error as Error).message,(error as Error).message,409);}
  const queries:BatchItem<"sqlite">[]=[];
  if(["resolve","supersede","reverse"].includes(input.action)){if(input.action==="resolve"&&!input.batchId)throw new ResolutionError("RESOLUTION_BATCH_REQUIRED","A proposed Sent-to-Bank batch is required.");if(input.batchId){const batch=(await db.select().from(paymentBatches).where(eq(paymentBatches.id,input.batchId)).limit(1))[0];if(!batch||batch.status!=="Sent to Bank")throw new ResolutionError("RESOLUTION_BATCH_INELIGIBLE","Only a Sent-to-Bank batch can be proposed.");if(batch.payableAmountPaisa!==row.record.paidAmountPaisa)throw new ResolutionError("TOLERANCE_OVERRIDE_PROHIBITED","Manual resolution cannot override exact PKR 0.00 tolerance.");}const target=input.action==="resolve"?"Resolved":input.action==="supersede"?"Superseded":"Reversed";queries.push(db.insert(reconciliationResolutions).values({id:uid(),reconciliationId:input.reconciliationId,action:input.action,reason:input.reason.trim(),evidenceUploadId:input.evidenceUploadId,proposedBatchId:input.batchId??row.result.batchId,requestedBy:input.user.id,approvedBy:null,previousStatus:row.result.status,resultingStatus:target,correlationId,createdAt:now}),db.update(reconciliationResults).set({status:"Pending Approval",updatedAt:now}).where(eq(reconciliationResults.id,input.reconciliationId)));}
  else if(input.action==="return"){if(!pending)throw new ResolutionError("RESOLUTION_REQUEST_NOT_FOUND","Pending request not found.");queries.push(db.update(reconciliationResults).set({status:"Returned",updatedAt:now}).where(eq(reconciliationResults.id,input.reconciliationId)),db.update(reconciliationResolutions).set({approvedBy:input.user.id,resultingStatus:"Returned"}).where(eq(reconciliationResolutions.id,pending.id)));}
  else if(input.action==="reopen"){queries.push(db.insert(reconciliationResolutions).values({id:uid(),reconciliationId:input.reconciliationId,action:"reopen",reason:input.reason.trim(),evidenceUploadId:input.evidenceUploadId,proposedBatchId:null,requestedBy:input.user.id,approvedBy:null,previousStatus:row.result.status,resultingStatus:"Reopened",correlationId,createdAt:now}),db.update(reconciliationResults).set({status:"Reopened",outcome:row.result.outcome==="Matched"?"Reversed or Superseded":row.result.outcome,updatedAt:now}).where(eq(reconciliationResults.id,input.reconciliationId)));}
  else {if(!pending)throw new ResolutionError("RESOLUTION_REQUEST_NOT_FOUND","Pending request not found.");const target=pending.resultingStatus,approvedBatch=pending.proposedBatchId?(await db.select().from(paymentBatches).where(eq(paymentBatches.id,pending.proposedBatchId)).limit(1))[0]:undefined;queries.push(db.update(reconciliationResolutions).set({approvedBy:input.user.id}).where(eq(reconciliationResolutions.id,pending.id)),db.update(reconciliationResults).set({status:target==="Resolved"?"Reconciled":target,outcome:target==="Resolved"?"Matched":"Reversed or Superseded",batchId:target==="Resolved"?pending.proposedBatchId:row.result.batchId,expectedAmountPaisa:target==="Resolved"?approvedBatch?.payableAmountPaisa:row.result.expectedAmountPaisa,variancePaisa:target==="Resolved"&&approvedBatch?row.record.paidAmountPaisa-approvedBatch.payableAmountPaisa:row.result.variancePaisa,reconciledBy:target==="Resolved"?input.user.id:row.result.reconciledBy,updatedAt:now}).where(eq(reconciliationResults.id,input.reconciliationId)));if(target==="Resolved"&&pending.proposedBatchId){queries.push(db.update(paymentBatches).set({status:"Processed Successfully",updatedAt:now}).where(and(eq(paymentBatches.id,pending.proposedBatchId),eq(paymentBatches.status,"Sent to Bank"))));const links=await db.select({caseId:cases.id,sourceUploadId:cases.sourceUploadId,breakupId:paymentBatchBookingBreakups.id}).from(paymentBatchCases).innerJoin(cases,eq(cases.id,paymentBatchCases.caseId)).innerJoin(paymentBatchBookingBreakups,and(eq(paymentBatchBookingBreakups.batchId,paymentBatchCases.batchId),eq(paymentBatchBookingBreakups.bookingDate,cases.bookingDate))).where(eq(paymentBatchCases.batchId,pending.proposedBatchId));for(const link of links)queries.push(db.insert(reconciliationCaseLinks).values({reconciliationId:input.reconciliationId,caseId:link.caseId,sourceUploadId:link.sourceUploadId,bookingBreakupId:link.breakupId}),db.update(cases).set({status:"Processed Successfully",updatedAt:now}).where(eq(cases.id,link.caseId)));}if(target==="Reversed"&&row.result.batchId)queries.push(db.update(paymentBatches).set({status:"Reconciliation Exception",updatedAt:now}).where(eq(paymentBatches.id,row.result.batchId)),db.update(cases).set({status:"Reconciliation Exception",updatedAt:now}).where(and(eq(cases.status,"Processed Successfully"),inArray(cases.id,db.select({id:paymentBatchCases.caseId}).from(paymentBatchCases).where(eq(paymentBatchCases.batchId,row.result.batchId))))));}
  const to=input.action==="approve"?(pending?.resultingStatus??"Resolved"):input.action==="return"?"Returned":input.action==="reopen"?"Reopened":"Pending Approval";queries.push(db.insert(statusHistory).values({id:uid(),entityType:"reconciliation",entityId:input.reconciliationId,fromStatus:row.result.status,toStatus:to,changedBy:input.user.id,reason:input.reason.trim(),correlationId,changedAt:now}),db.insert(auditEvents).values({id:uid(),actorId:input.user.id,action:`RECONCILIATION_${input.action.toUpperCase()}`,entityType:"reconciliation",entityId:input.reconciliationId,beforeJson:JSON.stringify({status:row.result.status}),afterJson:JSON.stringify({status:to,evidenceUploadId:input.evidenceUploadId}),reason:input.reason.trim(),correlationId,ipAddress:null,occurredAt:now}));await db.batch(queries as [BatchItem<"sqlite">,...BatchItem<"sqlite">[]]);return{status:to,correlationId};
}
