import { normalizeSpreadsheetDate, parseXlsx, SpreadsheetError } from "./spreadsheet.ts";
import { parsePaisa, type ConfirmationRecord } from "./reconciliation-controls.ts";

export type ParsedScbRecord = { recordNumber: number; evidenceLocation: string; raw: Record<string, string>; normalized: ConfirmationRecord };
export class ScbParsingError extends Error { code: string; constructor(code: string, message: string) { super(message); this.code=code; } }
const aliases: Record<string, keyof Record<string,string>> = { bankreference:"bankReference",reference:"bankReference",paymentdate:"paymentDate",referencedate:"paymentDate",beneficiaryname:"beneficiaryName",beneficiaryaccount:"beneficiaryAccount",accountiban:"beneficiaryAccount",iban:"beneficiaryAccount",paidamount:"paidAmount",amount:"paidAmount",embassy:"embassyReference",embassyreference:"embassyReference",consulate:"embassyReference",vac:"vacReference",location:"vacReference",vaclocation:"vacReference",narrative:"narrative",paymentnarrative:"narrative" };
const key = (value:string) => value.toLowerCase().replace(/[^a-z0-9]/g,"");
export function normalizeScbDate(value:string):string { const v=value.trim().replace(/\s+/g," "); let y:number,m:number,d:number; let hit=v.match(/^(\d{4})-(\d{2})-(\d{2})$/); if(hit){[,y,m,d]=hit.map(Number);} else if((hit=v.match(/^(\d{2})[-/](\d{2})[-/](\d{4})$/))){d=Number(hit[1]);m=Number(hit[2]);y=Number(hit[3]);} else { hit=v.match(/^(\d{1,2})[ -]([A-Za-z]{3,9})[ ,.-]+(\d{4})$/); if(!hit)throw new ScbParsingError("SCB_PAYMENT_DATE_INVALID","Date must be ISO, DD-MM-YYYY, DD/MM/YYYY, or day-month-name-year."); const months=["january","february","march","april","may","june","july","august","september","october","november","december"], token=hit[2].toLowerCase(),idx=months.findIndex(name=>name===token||name.slice(0,3)===token);if(idx<0)throw new ScbParsingError("SCB_PAYMENT_DATE_INVALID","Unknown month name.");d=Number(hit[1]);m=idx+1;y=Number(hit[3]);} const date=new Date(Date.UTC(y,m-1,d));if(date.getUTCFullYear()!==y||date.getUTCMonth()!==m-1||date.getUTCDate()!==d)throw new ScbParsingError("SCB_PAYMENT_DATE_INVALID","Date is not a real calendar date.");return `${y.toString().padStart(4,"0")}-${m.toString().padStart(2,"0")}-${d.toString().padStart(2,"0")}`; }
function normalize(raw:Record<string,string>):ConfirmationRecord { return {bankReference:(raw.bankReference??"").trim().toUpperCase(),paymentDate:normalizeScbDate(raw.paymentDate??""),beneficiaryName:(raw.beneficiaryName??"").trim().replace(/\s+/g," "),beneficiaryAccount:(raw.beneficiaryAccount??"").trim().toUpperCase().replace(/\s+/g,""),paidAmountPaisa:parsePaisa((raw.paidAmount??"").replace(/[ ,]/g,"")),embassyReference:raw.embassyReference?.trim()||undefined,vacReference:raw.vacReference?.trim()||undefined,narrative:raw.narrative?.trim()||undefined}; }
function csvRows(text:string){if(text.length>10*1024*1024)throw new ScbParsingError("SCB_FILE_LIMIT","SCB text exceeds 10 MB.");const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell="";}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);if(rows.length>25000)throw new ScbParsingError("SCB_ROW_LIMIT","SCB row limit exceeded.");row=[];cell="";}else cell+=c;}if(quoted)throw new ScbParsingError("SCB_CSV_MALFORMED","CSV contains an unterminated quoted field.");row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows;}
function mapTable(rows:string[][],location:(index:number)=>string):ParsedScbRecord[]{if(rows.length<2)throw new ScbParsingError("SCB_EMPTY_FILE","Evidence must contain a header and record.");const headers=rows[0].map(h=>aliases[key(h)]);return rows.slice(1).map((values,index)=>{const raw:Record<string,string>={};headers.forEach((field,i)=>{if(field)raw[field]=values[i]?.trim()??"";});return{recordNumber:index+2,evidenceLocation:location(index+2),raw,normalized:normalize(raw)};});}
export function parseScbCsv(bytes:Uint8Array){return mapTable(csvRows(new TextDecoder("utf-8",{fatal:true}).decode(bytes)),row=>`CSV row ${row}`);}
export function parseScbXlsx(bytes:Uint8Array){try{const book=parseXlsx(bytes,["SCB Confirmation","Confirmation","Sheet1"]),headers=book.rows[0]?.map(c=>aliases[key(c?.value??"")]),rows=book.rows.map((row,rowIndex)=>row.map((cell,index)=>rowIndex>0&&headers?.[index]==="paymentDate"&&cell?normalizeSpreadsheetDate(cell,book.date1904):cell?.value??""));return mapTable(rows,row=>`XLSX ${book.worksheet} row ${row}`);}catch(error){if(error instanceof ScbParsingError)throw error;const detail=error instanceof SpreadsheetError?error.code:"XLSX_PARSING_FAILED";throw new ScbParsingError(`SCB_${detail}`,error instanceof Error?error.message:"XLSX cannot be parsed safely.");}}
const pdfLiteral=(value:string)=>value.replace(/\\([nrtbf()\\])/g,(_,c:string)=>({n:"\n",r:"\r",t:"\t",b:"\b",f:"\f","(":"(",")":")","\\":"\\"}[c as "n"|"r"|"t"|"b"|"f"|"("|")"|"\\"]??c)).replace(/\\([0-7]{1,3})/g,(_,n)=>String.fromCharCode(parseInt(n,8)));
export function parseScbPdf(bytes:Uint8Array){if(bytes.length>10*1024*1024)throw new ScbParsingError("SCB_PDF_LIMIT","PDF exceeds 10 MB.");const text=new TextDecoder("latin1").decode(bytes);if(!text.startsWith("%PDF-"))throw new ScbParsingError("SCB_PDF_UNREADABLE","PDF signature is missing.");const pageObjects=[...text.matchAll(/\d+\s+\d+\s+obj([\s\S]*?)endobj/g)].filter(m=>/\/Type\s*\/Page\b/.test(m[1]));const pages=pageObjects.length||1,values:string[]=[];for(const stream of text.matchAll(/stream\r?\n([\s\S]*?)\r?\nendstream/g)){const streamText=stream[1];if(/\/FlateDecode/.test(text.slice(Math.max(0,(stream.index??0)-300),stream.index)))throw new ScbParsingError("SCB_PDF_COMPRESSED_UNSUPPORTED","Compressed PDF streams require an approved bounded parser.");for(const item of streamText.matchAll(/\((?:\\.|[^\\)])*\)\s*Tj|\[(.*?)\]\s*TJ/g)){const segment=item[0];for(const literal of segment.matchAll(/\(((?:\\.|[^\\)])*)\)/g))values.push(pdfLiteral(literal[1]));}}if(!values.length)throw new ScbParsingError("SCB_PDF_IMAGE_ONLY","PDF has no supported text operators; scanned/image-only or encoded-font PDFs require authorized OCR/parser support.");const content=values.join("\n"),raw:Record<string,string>={};for(const line of content.split(/\r?\n/)){const match=line.match(/^\s*([^:]+):\s*(.*?)\s*$/);if(match){const field=aliases[key(match[1])];if(field)raw[field]=match[2];}}if(!raw.bankReference)throw new ScbParsingError("SCB_PDF_STRUCTURE_UNSUPPORTED","PDF text is readable but does not use supported SCB label/value fields.");return[{recordNumber:1,evidenceLocation:`PDF page 1 of ${pages}`,raw,normalized:normalize(raw)}];}
export function parseScbEvidence(bytes:Uint8Array,fileName:string,mediaType:string){const lower=fileName.toLowerCase();if(mediaType.includes("csv")||lower.endsWith(".csv"))return parseScbCsv(bytes);if(mediaType.includes("spreadsheet")||lower.endsWith(".xlsx"))return parseScbXlsx(bytes);if(mediaType.includes("pdf")||lower.endsWith(".pdf"))return parseScbPdf(bytes);throw new ScbParsingError("SCB_FORMAT_UNSUPPORTED","Only UTF-8 CSV, structured XLSX, and supported machine-readable PDF are accepted.");}
export function duplicateBankReferences(records:ParsedScbRecord[]){const seen=new Set<string>(),duplicates:string[]=[];for(const item of records){const ref=item.normalized.bankReference.toUpperCase();if(seen.has(ref))duplicates.push(ref);seen.add(ref);}return duplicates;}
